-- START --

CREATE SCHEMA car_dealer;
USE car_dealer;

-- READ DATA --
SELECT * FROM car_details;

-- TO GET A COUNT OF TOTAL CARS --
SELECT COUNT(*) FROM car_details;

-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVAILABLE IN 2023? --
SELECT COUNT(*) FROM car_details WHERE year=2023;

-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS ARE AVAILABLE IN 2020,2021,2022 --
SELECT COUNT(*) FROM car_details WHERE year IN(2020,2021,2022) GROUP BY year;

-- CLIENT ASKED TO PRINT THE TOTAL CARS IN EACH YEAR --
SELECT year,COUNT(*) FROM car_details GROUP BY year;

-- CLIENT ASKED TO PRINT THE DIESEL CARS IN 2020 --
SELECT COUNT(*) FROM car_details WHERE year = 2020 AND fuel = "Diesel";

-- CLIENT ASKED TO PRINT THE PETROL CARS IN 2020 --
SELECT COUNT(*) FROM car_details WHERE year=2020 AND fuel="Petrol";

-- MANAGER ASKED TO PRINT ALL THE FUEL CARS IN EACH YEAR --
SELECT year,fuel,COUNT(*) FROM car_details WHERE fuel IN("Petrol","Diesel","CNG") GROUP BY year,fuel;

-- MANAGER ASKED TO PRINT THE YEAR WHICH HAD MORE THAN 100 CAES --
SELECT year,COUNT(*) FROM car_details GROUP BY year HAVING count(*)>100;

-- THE MANAGER ASKED TO PRINT ALL THE CAR DETAILS COUNT BETWEEN 2015 AND 2023 --
SELECT COUNT(*) FROM car_details WHERE year BETWEEN 2015 AND 2023;

-- THE MANAGER ASKED TO PRINT ALL THE CAR DETAILS BETWEEN 2015 AND 2023 --
SELECT * FROM car_details WHERE year BETWEEN 2015 AND 2023;

-- END --


